#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.21.130:3306/gulimall_pms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: gulimall-product
#
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#
#server:
#  port: 10001
#
#logging:
#  level:
#    com.atguigu.gulimall: debug

#
#apollo.bootstrap.enabled: true


#spring.redisson.address: redis://127.0.0.1:6379
#spring.redisson.password:


anti:
  reptile:
    manager:
      enabled: true
      globalFilterMode: true
      ip-rule:
        request-max-size: 5
        lock-expire: 30
        ignore-ip: 127.0.0.1
spring:
  redisson:
    address: redis://127.0.0.1:6379
