#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    alicloud:
#      access-key: LTAI5tHaJFZYF6XqH3TSApj9
#      secret-key: H5NgEE6LLxzkFmdxRCmayv8p2qgJDf
#      oss:
#        endpoint: oss-cn-huhehaote.aliyuncs.com
#        bucket: gulimall-lyj0808
#
#  application:
#    name: gulimall-third-party
#
#server:
#  port: 30000
