#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    alicloud:

#      oss:
#        endpoint: oss-cn-huhehaote.aliyuncs.com
#        bucket: gulimall-lyj0808
#
#  application:
#    name: gulimall-third-party
#
#server:
#  port: 30000
